using UnityEngine;
using System.Collections;
using System.IO;

public class TurnInfo : MasterScript
{
	[HideInInspector]
	public int GP, raceGP, science, industry, money, planetsColonisedThisTurn, savedIterator;
	public float raceScience, raceIndustry, raceMoney;
	[HideInInspector]
	public string[,] planetRIM = new string[12,5];
	public string[,] mostPowerfulPlanets = new string[211,3];
	[HideInInspector]
	public GameObject[] ownedSystems = new GameObject[60];
	public bool endTurn;
	public Camera mainCamera;
	public Material nereidesMaterial, humansMaterial, selkiesMaterial;
	public Material materialInUse;
	
	public string playerRace, homeSystem;
	public int turn = 0, systemsInPlay = 0;

	void Start()
	{			
		RefreshPlanetPower();
	}

	public void RefreshPlanetPower()
	{
		for(int i = 0; i < 60; i++)
		{
			guiPlanScript = masterScript.systemList[i].systemObject.GetComponent<GUISystemDataScript>();
			
			guiPlanScript.UpdatePlanetPowerArray(i);
		}
	}

	public void PickRace() //Start of turn function. Race choice dictates starting planet and inherent bonuses as well as racial technologies.
	{
		if(playerRace == "Humans")
		{
			raceScience = 1;
			raceIndustry = 1;
			raceMoney = 2;
			raceGP = 3;
			homeSystem = "Sol";
			materialInUse = turnInfoScript.humansMaterial;
		}
		if(playerRace == "Selkies")
		{
			raceScience = 1;
			raceIndustry = 3;
			raceMoney = 2;
			raceGP = 2;
			homeSystem = "Heracles";
			materialInUse = turnInfoScript.selkiesMaterial;
		}
		if(playerRace == "Nereides")
		{
			raceScience = 6;
			raceIndustry = 2;
			raceMoney = 4;
			raceGP = 1;
			homeSystem = "Nepthys";
			materialInUse = turnInfoScript.nereidesMaterial;
		}
	}

	public void StartSystemPlanetColonise(Material playerMaterial, string homeSystem)
	{
		guiPlanScript = GameObject.Find (homeSystem).GetComponent<GUISystemDataScript>();
		
		for(int i = 0; i < 60; i++) //Find selected system and set it to owned
		{
			if(masterScript.systemList[i].systemName == homeSystem)
			{
				masterScript.systemList[i].systemObject.renderer.material = playerMaterial;

				++systemsInPlay;

				for(int j = 0; j < guiPlanScript.numPlanets; ++j) //Colonise ocean planet (earth).
				{
					if(masterScript.systemList[i].planetType[j] == "Ocean")
					{
						masterScript.systemList[i].planetColonised[j] = true;
						break;
					}
				}

				break;
			}
		}

		guiPlanScript.CheckOwnership();
	}

	public void TurnEnd(TurnInfo selectedPlayer) //This function accumulates all the SIM generated by each system to give an empire SIM value
	{		
		endTurn = true;

		for(int i = 0; i < 60; ++i)
		{
			if(masterScript.systemList[i].systemOwnedBy == null || masterScript.systemList[i].systemOwnedBy == "")
			{
				continue;
			}

			guiPlanScript = masterScript.systemList[i].systemObject.GetComponent<GUISystemDataScript>();
			techTreeScript = masterScript.systemList[i].systemObject.GetComponent<TechTreeScript>();
			heroScript = masterScript.systemList[i].systemObject.GetComponent<HeroScriptParent>();

			techTreeScript.ActiveTechnologies(selectedPlayer);
			guiPlanScript.SystemSIMCounter(i);
			guiPlanScript.CheckUnlockedTier();

			science += (int)guiPlanScript.totalSystemScience;
			industry += (int)guiPlanScript.totalSystemIndustry;
			money += (int)guiPlanScript.totalSystemMoney;
		}

		turnInfoScript.SortSystemPower();
		
		GP += raceGP;

		planetsColonisedThisTurn = 0;

		endTurn = false;
	}

	public void SortSystemPower()
	{
		int i, j; 
		string[] temp = new string[3];

		for(i = 210; i >= 0; --i)
		{
			bool swaps = false;

			for(j = 1; j <= i; ++j)
			{
				if(float.Parse (mostPowerfulPlanets[j-1, 2]) < float.Parse (mostPowerfulPlanets[j, 2]))
				{
					temp[0] = mostPowerfulPlanets[j-1, 0];
					temp[1] = mostPowerfulPlanets[j-1, 1].ToString();
					temp[2] = mostPowerfulPlanets[j-1, 2].ToString();

					mostPowerfulPlanets[j-1, 0] = mostPowerfulPlanets[j, 0];
					mostPowerfulPlanets[j-1, 1] = mostPowerfulPlanets[j, 1];
					mostPowerfulPlanets[j-1, 2] = mostPowerfulPlanets[j, 2];

					mostPowerfulPlanets[j, 0] = temp[0];
					mostPowerfulPlanets[j, 1] = temp[1];
					mostPowerfulPlanets[j, 2] = temp[2];

					swaps = true;
				}
			}

			if(swaps == false)
			{
				break;
			}
		}
	}
}
